/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './index';
import * as import2 from '@angular/common';
class QrScannerModuleInjector extends import0.ɵNgModuleInjector<import1.QrScannerModule> {
  _CommonModule_0:import2.CommonModule;
  _QrScannerModule_1:import1.QrScannerModule;
  __NgLocalization_2:import2.NgLocaleLocalization;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _NgLocalization_2():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_2 == null)) { (this.__NgLocalization_2 = new import2.NgLocaleLocalization(this.parent.get(import0.LOCALE_ID))); }
    return this.__NgLocalization_2;
  }
  createInternal():import1.QrScannerModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._QrScannerModule_1 = new import1.QrScannerModule();
    return this._QrScannerModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import1.QrScannerModule)) { return this._QrScannerModule_1; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_2; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const QrScannerModuleNgFactory:import0.NgModuleFactory<import1.QrScannerModule> = new import0.NgModuleFactory<any>(QrScannerModuleInjector,import1.QrScannerModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvdHVsa2FzL1B1YmxpYy9Qcm9qZWN0cy9nZW50YWxpYS9hbmd1bGFyMi1xcnNjYW5uZXIvaW5kZXgubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS90dWxrYXMvUHVibGljL1Byb2plY3RzL2dlbnRhbGlhL2FuZ3VsYXIyLXFyc2Nhbm5lci9pbmRleC50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
