/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './qrscanner.component';
const styles_QrScannerComponent:any[] = ([] as any[]);
export const RenderType_QrScannerComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_QrScannerComponent,
  data: {}
}
);
export function View_QrScannerComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵted((null as any),['\n    '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),0,'canvas',[
      [
        'hidden',
        'true'
      ]
      ,
      [
        'id',
        'qr-canvas'
      ]

    ]
    ,[
      [
        8,
        'width',
        0
      ]
      ,
      [
        8,
        'height',
        0
      ]

    ]
    ,(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n    '])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),0,'div',[[
        'id',
        'outdiv'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n    '])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),0,'div',[[
        'id',
        'mainbody'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n']))
  ]
  ,(null as any),(ck,v) => {
    var co:import1.QrScannerComponent = v.component;
    const currVal_0:any = import0.ɵinlineInterpolate(1,'',co.width,'');
    const currVal_1:any = import0.ɵinlineInterpolate(1,'',co.height,'');
    ck(v,1,0,currVal_0,currVal_1);
  });
}
function View_QrScannerComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'qr-scanner',([] as any[]),(null as any),(null as any),(null as any),View_QrScannerComponent_0,RenderType_QrScannerComponent)),
    import0.ɵdid(122880,(null as any),0,import1.QrScannerComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const QrScannerComponentNgFactory:import0.ComponentFactory<import1.QrScannerComponent> = import0.ɵccf('qr-scanner',import1.QrScannerComponent,View_QrScannerComponent_Host_0,{
  width: 'width',
  height: 'height',
  facing: 'facing'
}
,{onRead: 'onRead'},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvdHVsa2FzL1B1YmxpYy9Qcm9qZWN0cy9nZW50YWxpYS9hbmd1bGFyMi1xcnNjYW5uZXIvc3JjL3Fyc2Nhbm5lci5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS90dWxrYXMvUHVibGljL1Byb2plY3RzL2dlbnRhbGlhL2FuZ3VsYXIyLXFyc2Nhbm5lci9zcmMvcXJzY2FubmVyLmNvbXBvbmVudC50cyIsIm5nOi8vL2hvbWUvdHVsa2FzL1B1YmxpYy9Qcm9qZWN0cy9nZW50YWxpYS9hbmd1bGFyMi1xcnNjYW5uZXIvc3JjL3Fyc2Nhbm5lci5jb21wb25lbnQudHMuUXJTY2FubmVyQ29tcG9uZW50Lmh0bWwiLCJuZzovLy9ob21lL3R1bGthcy9QdWJsaWMvUHJvamVjdHMvZ2VudGFsaWEvYW5ndWxhcjItcXJzY2FubmVyL3NyYy9xcnNjYW5uZXIuY29tcG9uZW50LnRzLlFyU2Nhbm5lckNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuICAgIDxjYW52YXMgaWQ9XCJxci1jYW52YXNcIiB3aWR0aD1cInt7d2lkdGh9fVwiIGhlaWdodD1cInt7aGVpZ2h0fX1cIiBoaWRkZW49XCJ0cnVlXCI+PC9jYW52YXM+XG4gICAgPGRpdiBpZD1cIm91dGRpdlwiPjwvZGl2PlxuICAgIDxkaXYgaWQ9XCJtYWluYm9keVwiPjwvZGl2PlxuIiwiPHFyLXNjYW5uZXI+PC9xci1zY2FubmVyPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7SUNBQTtJQUNJO01BQUE7UUFBQTtRQUFBO01BQUE7O01BQUE7UUFBQTtRQUFBO01BQUE7O0lBQUE7S0FBQTtNQUFBO1FBQUE7UUFBQTtRQUFBO01BQUE7O01BQUE7UUFBQTtRQUFBO1FBQUE7TUFBQTs7SUFBQTtLQUFBO0lBQW9GO01BQ3BGO1FBQUE7UUFBQTtNQUFBO0lBQUE7SUFBdUI7TUFDdkI7UUFBQTtRQUFBO01BQUE7SUFBQTtJQUF5Qjs7OztJQUZGO0lBQWtCO0lBQXpDLFNBQXVCLFVBQWtCLFNBQXpDOzs7OztJQ0RKO2dCQUFBOzs7SUFBQTs7Ozs7Ozs7In0=
